id: P4C048CC8
initial_creation_type: ocr
source_metadata:
  volumes:
    9f1068cff02142e39beb8c11ede7e5d4:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བྱང་ཆུབ་ཀྱི་སེམས་བསྒོམ་པ།
      total_pages: 1902
      volume_number: 64
